"""add-users

Revision ID: f01d58840269
Revises: 3c64ca435aae
Create Date: 2026-03-07 15:36:10.593524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f01d58840269'
down_revision: Union[str, None] = '3c64ca435aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), default=False, nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_user_email'", "users", ["email"], unique=True)
    op.create_index("ix_user_api_key", "users", ["api_key"], unique=True)

    op.create_table('service_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), default=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_service_accounts_api_key", "service_accounts", ["api_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.drop_index(op.f('ix_user_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_account_api_key'), table_name='service_accounts')
    op.drop_table('service_accounts')
    # ### end Alembic commands ###
